services:
    laravel_app:
        container_name: laravel_identity_flow
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        env_file:
            - .env
        volumes:
            - .:/var/www/html
        depends_on:
            - postgres_identity_flow
        restart: unless-stopped

    postgres_identity_flow:
        container_name: postgres_identity_flow
        image: postgres:15-alpine
        ports:
            - "5433:5432"
        env_file:
            - .env
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    postgres_data: {}
